id: assignToModerators
name: GitOps.PullRequestIssueManagement
description: Add keywords to this file to restrict packages that have been removed from the repository for a reason
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - assignTo:
              user: stephengillie
