# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: TrainerRoad.TrainerRoad
PackageVersion: 2023.1.2.166
PackageLocale: en-US
Publisher: TrainerRoad LLC
PackageName: TrainerRoad
License: Proprietary
Copyright: Copyright © 2023 TrainerRoad LLC
ShortDescription: Cycling's Most Effective Training App
ManifestType: defaultLocale
ManifestVersion: 1.2.0

